<!doctype html>
<html xmlns:fb="http://www.facebook.com/2008/fbml">
  <head>
    <title>Friends Lists</title>
    <style>
      body {
        font-family: 'Lucida Grande', Verdana, Arial, sans-serif;
      }
      h1 a {
        text-decoration: none;
        color: #3b5998;
      }
      h1 a:hover {
        text-decoration: underline;
      }
    </style>
  </head>
  <body>

<?php

$user = $this->facebook->api( '/me' );

$users_likesList;

if ($user){
// User is logged in

        try {

            // Show this friend's profile pic
            echo '<br/><br/><img src="https://graph.facebook.com/' . $this->user_id . '/picture"><br/><br/>';

            // Show this friend's user's info
            $friends_info = $this->facebook->api('/' . $this->user_id );

            echo '<h3>User Info</h3>';
            print_r( $friends_info );
            echo '<br/><br/>';

            echo '<h3>Search Term Results</h3>';
            
            $n = 1;

            foreach( $this->topCategoriesHits as $aSearchTerm ){

                echo '<a href="/gift/searchtest/numberOfItems/20/searchIndex/1/priceRange/[1,1000]/q/' . urlencode( $aSearchTerm['name'] ) . '">' . $n . ') ' . $aSearchTerm['name'] . '</a><br/>';

                $n++;
            }

        } catch (FacebookApiException $e) {
                error_log($e);
        }

} // User is logged in


?>
  </body>
</html>

