
<form action="/data/index/class/Crud/method/create/accessToken/<?php echo $this->facebook->getAccessToken(); ?>" method="POST">
    <input type="text" name="tableName" value="aTable"/><br/>

    <input type="text" name="key_items_id_seq" value="1111"/><br/>
    <input type="text" name="key_user_id" value="12345"/><br/>
    <input type="text" name="key_type" value="click"/><br/>
    <input type="text" name="key_datetime_created" value="now()"/><br/>
    <input type="text" name="key_datetime_modified" value="now()"/><br/>

    <input type="submit" name="submit" value="submit"/><br/>

</form>
